### ISSUE TITLE
Global configuration for all my projects

### ISSUE THREAD

**Issue by maximn** [olafurpg/scalafmt#239]
My problem is that I have 10s of projects and I don't want to maintain a copy of the .scalafmt file in each project.

The solution can be in machine level (i.e. global .scalafm file) or IntelliJ level (plugin configuration).

**Comment by olafurpg** [comment]
I agree this could be handy. However, consider that a lack of a .scalafmt file in your project will make it hard for other contributors to use the same configuration as you.

I welcome contributions on this issue, since it's not a feature I would use myself and implementing it requires no knowledge about the formatting internals. A good start would be to setup the [intellij](https://github.com/olafurpg/scalafmt/tree/master/intellij) project and start hacking on [ScalafmtAction](https://github.com/olafurpg/scalafmt/blob/master/intellij/src/org/scalafmt/intellij/ScalafmtAction.scala). To test your changes, do Run > Run plugin.

I'm happy with either a global .scalafmt file or an IntelliJ level configuration, although I would say that a global .scalafmt file is probably easier to implement and it plays nicer with other editor integrations.

**Comment by maximn** [comment]
I think that if a project have .scalafmt file it should override the global setting so you can use both.

I'll try to have a look.

**Comment by olafurpg** [comment]
I agree, both should be possible. [Here](https://github.com/olafurpg/scalafmt/blob/master/intellij/src/org/scalafmt/intellij/ScalafmtAction.scala#L71) is the relevant line. A fallback to `$HOME/.scalafmt`should probably be a straightforward fix.

**Comment by olafurpg** [comment]
Closed in #246
