### ISSUE TITLE
Option to insert unicode arrows

### ISSUE THREAD

**Issue by easel** [olafurpg/scalafmt#277]
Scalariform has an option "RewriteArrowSymbols". It replaces => with ⇒, etc. 

I'd like an equivalent in scalafmt.

**Comment by olafurpg** [comment]
I personally dislike the unicode arrows for several reasons. Most importantly, unicode arrow are not present in your most standard keyboard layout (hence, a tool is needed to insert them). Also, editing in vim I often run `dt=` to delete up to a `=>` but when the arrow is unicode I can't do that.

I haven't heard a compelling reason why unicode symbol are better than regular ascii characters. I'm open to change my mind, so I assigned the "open for debate" label.

For now, my vote goes to encourage people to rewrite their unicode symbols to regular arrows:
```
find . -type f -name "*.scala" -exec sed -i '' "s/⇒/=>/" {} \;
```

PS. @easel Please use the thumbs up reaction instead of commenting +1.

**Comment by sjrd** [comment]
Given that scalafmt is not supposed to do anything but changing whitespace, does such a rewriting even enter the scope of the project?

**Comment by olafurpg** [comment]
True, but the AST remains unchanged. Also, scalafmt does have an option to poke into multiline stripMargin strings.

**Comment by sjrd** [comment]
> True, but the AST remains unchanged.

By that argument, I could also ask scalafmt to [insert `{}` around multi-line expressions](https://github.com/scala-js/scala-js/blob/master/CODINGSTYLE.md#braces) (and remove them for single-line expressions), to [make then and else branches agree on using `{}`](https://github.com/scala-js/scala-js/blob/master/CODINGSTYLE.md#ifelse) or [appropriately use `()` vs `{}` in for comprehensions](https://github.com/scala-js/scala-js/blob/master/CODINGSTYLE.md#for-comprehensions), couldn't I? Now, you told me those were out of scope.

I'm not complaining. I'm trying to understand the logic ;)

**Comment by olafurpg** [comment]
Hehe, valid point. I guess the logic has so far mostly relied on what's easiest to implement. Those rules in the Scala.js coding style require non-trivial changes to scalafmt's formatting algorithm while rewriting unicode arrows is quite straightforward to add.

**Comment by sjrd** [comment]
OK ^^

**Comment by easel** [comment]
I've found the unicode arrows a little easier to read, and since I have a tool to insert them I don't give it a second thought. My impression has been that scalafmt is trying to be an heir apparently the more-or-less unmaintained scalariform, so feature parity would be nice.

**Comment by olafurpg** [comment]
So far, the only intersection of options in scalariform and scalafmt is case arrow alignment. Feature parity has not been an objective, since those happy with scalariform can continue to use scalariform.

I'm still willing to consider adding option, but I would like to get more feedback from users who want it. I know that akka uses unicode arrows and I would be interested to hear their reasoning for that.

**Comment by anna-zzz** [comment]
Our project uses unicode arrows, and we love them (or I force everyone to love them, IDK...) because:
- they're one symbol instead of two and they don't make sense parted like `=` plus `>`, only as `⇒` (especially if you navigate a line using arrow keys)
- they're beautiful (this one is legit, eh?)
- mother of god unicode symbols in my code ♥ !!! 

Also, that heart-shaped unicode bit and the arrow above were legitimately typed in a few keystrokes with XCompose which is buried so deep in X server I can't even call it a separate tool.

I don't want to include any `find ...` script as a part of our code because scalafmt does an awesome job grooming our code style without any weird supports like custom scripts and commit hooks.

So I'd love to see this feature, maybe just disable it by default @olafurpg?

**Comment by olafurpg** [comment]
I would like to add one more argument against unicode arrows: some fonts don't support them. For example, the font `Inconsolata` (a [popular coding font](http://hivelogic.com/articles/top-10-programming-fonts/)) prints them like `=`

<img width="265" alt="screen shot 2016-06-21 at 23 14 06" src="https://cloud.githubusercontent.com/assets/1408093/16246628/4f0e7d7c-3806-11e6-9f21-684f7f02162a.png">

The red `=` on line 2 is a unicode arrow, very confusing. In the end, my biggest gripe against unicode arrows is accessibility. Sure, unicode symbols can look super sexy if your code formatter or keyboard is setup correctly. But in the end, I think it's more important that you can open up a source file in any text editor, with any keyboard layout and start hacking.

(again, I'm happy to add this as an optional flag, I just want make it clear that I really don't like unicode arrows 😄  )

**Comment by lespea** [comment]
Yeah I don't think anybody wants it as a default but I don't see the harm in it being an option.  If you don't like them just don't enable them.

**Comment by olafurpg** [comment]
I added a generic --rewriteTokens flag to rewrite arbitrary tokens into other tokens. The default style contains no rewrite rules, to get unicode arrows you can set

```
--rewriteTokens =>;⇒,<-;←
```

**Comment by ryan-williams** [comment]
Happy to see this is supported, thanks!

What can I put in `.scalafmt.conf` to correspond to the cmdline flag `--rewriteTokens =>;⇒,<-;←`?
