### ISSUE TITLE
scalafmt is not idempotent for this example

### ISSUE THREAD

**Issue by dabd** [olafurpg/scalafmt#278]
Using settings: 
--maxColumn 140

Original:
```scala
trait SelfEmploymentsBalancingChargesController extends BaseController with Links {

  val balancingChargesJson = toJson(
    balancingCharges.map(balancingCharge =>
      halResource(
        obj(),
        Seq(HalLink("self",
          selfEmploymentSummaryTypeIdHref(saUtr, taxYear, seId, BalancingChargesSummaryType, balancingCharge.id.get))))))
}

```

Scalafmt:
```scala
trait SelfEmploymentsBalancingChargesController extends BaseController with Links {

  val balancingChargesJson = toJson(
      balancingCharges.map(balancingCharge =>
            halResource(obj(),
                        Seq(HalLink("self",
                                    selfEmploymentSummaryTypeIdHref(
                                        saUtr, taxYear, seId, BalancingChargesSummaryType, balancingCharge.id.get))))))
}
```

When applying the formatter repeatedly the output varies between:
```scala
trait SelfEmploymentsBalancingChargesController extends BaseController with Links {

  val balancingChargesJson = toJson(
      balancingCharges.map(balancingCharge =>
            halResource(
                obj(),
                Seq(HalLink("self",
                            selfEmploymentSummaryTypeIdHref(saUtr, taxYear, seId, BalancingChargesSummaryType, balancingCharge.id.get))))))
}

```
and

```scala
trait SelfEmploymentsBalancingChargesController extends BaseController with Links {

  val balancingChargesJson = toJson(
      balancingCharges.map(balancingCharge =>
            halResource(obj(),
                        Seq(HalLink("self",
                                    selfEmploymentSummaryTypeIdHref(
                                        saUtr, taxYear, seId, BalancingChargesSummaryType, balancingCharge.id.get))))))
}
```

Using
* 0.2.5

**Comment by olafurpg** [comment]
What settings are you using?

**Comment by olafurpg** [comment]
I was able to reproduce the issue. I will try to fix this asap, thanks for reporting.

**Comment by olafurpg** [comment]
I've tracked down the issue to scalafmt's escape hatch when the search space grows out of bounds. The escape hatch seems to be non-idempotent in some cases (not triggered by the 1.2 million LOC in my tests).

Each application, select and lambda (8 nested in your example) increases the search space by an exponential factor. For details why this is a challenge, see http://journal.stuffwithstuff.com/2015/09/08/the-hardest-program-ive-ever-written/

The best solution I can come up with is to change the default behaviour to leave entire troublesome statements unformatted instead of doing a best-effort like it currently does. Once scalafmt's search algorithm improves that escape hatch will be triggered in fewer cases. The best-effort formatting can then be enabled via a flag at the risk of getting non-idempotent formatting.

**Comment by olafurpg** [comment]
FWIW, here's how scalafmt sees the statement

<img width="1178" alt="screen shot 2016-05-25 at 19 19 34" src="https://cloud.githubusercontent.com/assets/1408093/15549993/9f40fdcc-22af-11e6-8706-8ac935f65c2b.png">

The escape hatch is triggered between `saUtr` and `,` when the search algorithm has visited that pair over 200 times. Disabling the escape hatch makes the statement format optimally after ~5k state visits, which isn't so bad at all. But you only need a few more nestings to make that search intractable.

**Comment by olafurpg** [comment]
@dabd Note that scalafmt is still non-idempotent, see #339.
