### ISSUE TITLE
where is ScalafmtConfig scaladoc

### ISSUE THREAD

**Issue by windfansy** [olafurpg/scalafmt#300]
hello, i use scalafmt 0.2.5 , when i type `scalafmt --help`:
```
Style configuration options:
  -s <value> | --style <value>
        base style, must be one of: Set(Scala.js, default, defaultWithAlign)
  --maxColumn <value>
        See ScalafmtConfig scaladoc.
  --continuationIndentCallSite <value>
        See ScalafmtConfig scaladoc.
  --continuationIndentDefnSite <value>
        See ScalafmtConfig scaladoc.
```
but where can i find ScalafmtConfig scaladoc, i have no idea to set config options

**Comment by olafurpg** [comment]
I apologize, it was supposed to be ScalafmtStyle which is here https://github.com/olafurpg/scalafmt/blob/master/core/src/main/scala/org/scalafmt/ScalafmtStyle.scala.

This has been fixed on the website and for the next release. I will keep this issue open since I want to document each flag with clearer examples on the website.

**Comment by windfansy** [comment]
thanks a lot, it helps lot!
