### ISSUE TITLE
Enable sorting imports within braces

### ISSUE THREAD

**Issue by djspiewak** [olafurpg/scalafmt#304]
Original:
```scala
import foo.{Zilch, bar, Random, sand}
```

I would like the input to look like this:
```scala
import foo.{bar, sand, Random, Zilch}
```

----

While scalafmt clearly cannot reorder general import statements due to hierarchical import semantics, those semantics do not apply within braces as shown, so reordering is valid.

I can see two valid rules here:

- Alphabetical, with lower-case grouped
- Strictly alphabetical

I like the first option, and this seems to be relatively uncontroversial, but I can imagine some people prefer the second.  The first option is demonstrated above.  The second option would yield the following:

```scala
import foo.{bar, Random, sand, Zilch}
```

**Comment by olafurpg** [comment]
I agree that this would be a neat feature to add. To be frank however, this falls quite low on my priority list since I don't use brace grouped import statements 😜 I prefer to expand each import into separate lines. For that reason, I put the "help wanted" label.

Refactoring like this are usually done in the `FormatWriter`. However, I'm not sure if that's the best place for it, will need more time to think about it. I'm happy to help find a good solution if anyone is interested in taking a stab at this.

**Comment by djspiewak** [comment]
Oh I agree it's a pretty low priority thing!  Just thought I'd get it out there; wouldn't mind pitching in if I get the time down the line.

One of the reason to use the braces in the first place, btw, is to unambiguously avoid hierarchical imports.  :-)

**Comment by olafurpg** [comment]
Another cool trick to avoid hierarchical imports is just to never use them. Although, I'm definitely guilty of using them myself :)

**Comment by olafurpg** [comment]
#447 is a POC implemenatation to add this feature.

It uses strict alphabetical ordering, but I agree that grouping by lower-case identifiers looks nice. What do people think about this? I would prefer if we could all agree on one option instead of leaving it up for all users to make the choice.

The [implementation is ~20 LOC](https://github.com/olafurpg/scalafmt/pull/447/files#diff-bffc3623bd2dfb756870c947faa96458R18), which I think is pretty neat.

@djspiewak what do you think about the caveats? See https://github.com/olafurpg/scalafmt/pull/447/files#diff-78be7b1bd1467944197acf91cad3adaeR44

**Comment by olafurpg** [comment]
This rule is called `SortImports` and can be enabled like this

```
rewrite.rules = [SortImports]
```

using the new config system. I'll include more details in the release notes for 0.4.
