### ISSUE TITLE
failed to format

### ISSUE THREAD

**Issue by reactormonk** [olafurpg/scalafmt#319]
Clone https://github.com/scala-eveapi/eveapi
Checkout https://github.com/scala-eveapi/eveapi/commit/32586cebd1ff576980ce26a5d74fd44e908ea598

https://gist.github.com/reactormonk/2b0129d82cbf87a860a4e75e9f632d34

Using:
* 0.2.5
* --style default

**Comment by olafurpg** [comment]
I was able to reproduce the issue. It seems that only autogenerated files are affected, which is comforting at least.

Also, I think the error message should be clearer.

**Comment by olafurpg** [comment]
FYI, I won't be able to look at this properly until after a few weeks.

FWIW, scalafmt is blocked on this monster statement: https://github.com/scala-eveapi/eveapi/blob/master/xml/src/main/scala/eveapi/xml/char/ContactList/xmlprotocol.scala#L28-L37

<img width="713" alt="screen shot 2016-06-11 at 00 21 31" src="https://cloud.githubusercontent.com/assets/1408093/15980255/8c9c44b6-2f6a-11e6-9982-15f116194657.png">

The bug seems to be in `recurseOnBlocks`, not Router.

**Comment by olafurpg** [comment]
Note that scalafmt will still not format this file, but the cause now is a search state explosion instead of a bug in the formatting rules. Deeply nested computer generated code causes a lot of problems for the `--maxColumn` flag.
