### ISSUE TITLE
Function value (curlies) should not be split over multiple lines

### ISSUE THREAD

**Issue by hseeberger** [olafurpg/scalafmt#323]
Original:
```scala
def startSharding(system: ActorSystem, mediator: ActorRef, shardCount: Int): Unit = ClusterSharding(system).start(
  className[Flow],
  props(mediator),
  ClusterShardingSettings(system),
  { case (name: String, payload) => (name, payload) },
  { case (name: String, _) => (name.hashCode % shardCount).toString }
)
```

Scalafmt:
```scala
def startSharding(system: ActorSystem, mediator: ActorRef, shardCount: Int): Unit =
  ClusterSharding(system).start(
      className[Flow],
      props(mediator),
      ClusterShardingSettings(system), {
        case (name: String, payload) => (name, payload)
      }, { case (name: String, _)    => (name.hashCode % shardCount).toString }
  )
```

I would like the input to look like this:
```scala
def startSharding(system: ActorSystem, mediator: ActorRef, shardCount: Int): Unit =
  ClusterSharding(system).start(
      className[Flow],
      props(mediator),
      ClusterShardingSettings(system),
      { case (name: String, payload) => (name, payload) },
      { case (name: String, _)       => (name.hashCode % shardCount).toString }
  )
```

Using:
* 0.2.5
* --style defaultWithAlign --maxColumn 120 --spacesInImportCurlyBraces true

**Comment by olafurpg** [comment]
I agree that the expected output looks nicer. A quick experiment shows that it should be possible to let scalafmt keep the block on a single line if the block is already on a single line and it fits within the column limit. I'm gonna label this 0.2.7 since there's already lots of issues planned for the 0.2.6 release, which I would like to get out asap.

**Comment by hseeberger** [comment]
@olafurpg, thanks for the quick response. BTW, I don't expect alignment of `=>` here (like shown in the expected output), but if it works, it would be nice.

**Comment by olafurpg** [comment]
For some reason, I'm struggling to make this work for tricker cases like

```scala
  writeRead(
    // Use list because Array has a shitty toString
    { (b: List[Byte], os) => os.writePosVarInt(b.size); os.writeBytes(b.toArray) },
    { is =>
      val bytes = new Array[Byte](is.readPosVarInt)
      is.readFully(bytes)
      bytes.toList
    })
```

I don't want to spend more time on this issue since I am not so sure how common this coding pattern is. I'm gonna remove the milestone and add the help wanted label. The bug appears to be hidden somewhere deep inside the best-first search, which I try to avoid touching these days. If someone wants to take a stab at it you can work from my [323 branch](https://github.com/olafurpg/scalafmt/tree/323). However, you have been warned that the [best-first search](https://github.com/olafurpg/scalafmt/blob/master/core/src/main/scala/org/scalafmt/internal/BestFirstSearch.scala) is the hairiest part of the codebase, which I hope to refactor some day or (even better) remove entirely by using dynamic programming like `rfmt` does.

**Comment by olafurpg** [comment]
Nevermind my previous comment, I went out for a run and figured out the issue. It had nothing to do with the best-first search :)

Scalafmt will now allow curly block arguments to stay on a single line if they fit, the block will be formatted like before if it doesn't fit on a single line.

**Comment by hseeberger** [comment]
Running always helps ;-)
