### ISSUE TITLE
alignStripMarginStrings should respect pipe char on first line

### ISSUE THREAD

**Issue by hseeberger** [olafurpg/scalafmt#324]
Original:
```scala
"""|first
   |second""".stripMargin
```

Scalafmt:
```scala
"""|first
  |second""".stripMargin
```

I would like the input to look like this:
```scala
"""|first
   |second""".stripMargin
```

Using:
* 0.2.5
* --alignStripMarginStrings true

If the first character on the first line is a pipe character (strip margin character), the pipe characters on the following lines should be indented such that they are aligned with the pipe character on the fist line and not with the last double quote.

**Comment by olafurpg** [comment]
Huh, I've never seen the pipe used like that, but I kind of like it. This should be possible to accommodate in 0.2.7

**Comment by hseeberger** [comment]
Great! Using the pipe like that – which I have seen in several places – can help with readability a lot in specific situations. Looking forward to 0.2.7 ;-)

**Comment by olafurpg** [comment]
Finally got around to this issue :) If the first characters is a pipe the indentation increases by one space. It was tricker than I expected since I had to account for interpolated strings, which have a completely different structure compared to string literals. Let me know if you find any issues with this new feature.

**Comment by hseeberger** [comment]
Great stuff!
