### ISSUE TITLE
Support reformatting scalas files

### ISSUE THREAD

**Issue by OlegYch** [olafurpg/scalafmt#344]
Original:
```scala
/***
scalaVersion := "2.11.8"
 
*/
object Main extends App {
}

```

Scalafmt:
```scala
/***
scalaVersion := "2.11.8"
 
 */
object Main extends App {
}
  
```

I would like the input to look like this:
```scala
/***
scalaVersion := "2.11.8"
 
*/
object Main extends App {
}
```
ie, the closing comment should not have a space added
Using:
* 0.2.x
* --style default

**Comment by olafurpg** [comment]
It should be possible to add an option to disable docstring reformatting entirely. The current implementation assumes that all docstrings follow the convention that asterisks align somehow. I see this assumption is wrong for example with Scastie (cool project btw!). I'm happy to add this for 0.2.9 but since I'm traveling I won't be out for a while. If you're interested in taking a stab at it then

*  [here is the method](https://github.com/olafurpg/scalafmt/blob/b91d6fcd64147a9a74f2d7a47af612cc29bf3ef6/core/src/main/scala/org/scalafmt/internal/FormatWriter.scala#L49) that needs to change. Note that a `ScalafmtStyle` is in scope.
* a good name for the flag could be `--reformatDocstrings <true/false>`
* [The readme](https://github.com/olafurpg/scalafmt) has a tutorial on hacking on scalafmt, FWIW.

**Comment by OlegYch** [comment]
thanks! sorry i missed you earlier comment, will try a pr next time

**Comment by olafurpg** [comment]
It was a quick fix ;) hoping to get a small release out today
