### ISSUE TITLE
Default formatting produces too much code for arrays of literals

### ISSUE THREAD

**Issue by densh** [olafurpg/scalafmt#347]
Here a few examples of Scala Native codebase where the quality of formatted code leaves a lot to be desired size-wise:

https://github.com/scala-native/scala-native/blob/master/javalib/src/main/scala/java/lang/Character.scala#L547

https://github.com/siriux/scala-native/blob/7ea66ec1afebf5df19ae5896bbe462f8f96ea53f/javalib/src/main/scala/niocharset/UTF_8.scala#L42

Using:
* 0.2.5
* --style defaultWithAlign --javaDocs

**Comment by densh** [comment]
If it's array of primitive numbers or chars, it should just bin-pack it by default in my opinion. Having one literal per line is a massive overkill.

**Comment by olafurpg** [comment]
I agree that the output for Arrays.scala does not help readability and it would be great if scalafmt could automatically detect these situations to produce better formatting output.

> If it's array of primitive numbers or chars, it should just bin-pack it by default in my opinion

That's an interesting idea, but in terms of detecting when bin-packing should be used I think that rule will produce too many false positives and negatives. IMO, for now, Arrays.scala is a case where scalafmt should be disabled. Maybe with #315, instead of disabling scalafmt you will be able to enable bin-packing for that file only.

**Comment by densh** [comment]
These two are normal human-written code, they are not generated in any way.

**Comment by densh** [comment]
#315 is good enough fix for this issue.
