### ISSUE TITLE
Search state exploded

### ISSUE THREAD

**Issue by schickling** [olafurpg/scalafmt#353]
Hi there. First of all, thank you for putting so much work into this great project. It helps a lot!

When working on a file with deeper function nesting I'm getting the following error and `scalafmt` doesn't seem to take any effect. I assume that's due to the deeper function nesting as mentioned in the "Known Issues" section on the website. However I've ran into this problem quite a lot lately and would love to hear whether this is something you're working on.

![screen shot 2016-06-29 at 15 22 53](https://cloud.githubusercontent.com/assets/1567498/16453517/6050f9b8-3e0d-11e6-89b4-d8799e987cc6.png)

**Comment by olafurpg** [comment]
The latest release changed the behaviour for deeply nested function calls from best-effort formatting to failing fast. I don't know when I will work on handling deeper function nesting, but I've added a flag `--bestEffortInDeeplyNestedCode` in 0.2.9 to enable to best-effort formatting like it worked in the previous releases. You can give it a try, check that it's idempotent. I think it does a great job for most situations. I disabled it by default because it can sometimes produce bad output.

**Comment by schickling** [comment]
Hi @olafurpg. Thanks for getting back so quickly! How would you use this new option in Idea?

**Comment by olafurpg** [comment]
Good thing you reminded me of that. I updated the IntelliJ plugin to pick up non-style configuration just like style configuration in `.scalafmt`, see https://olafurpg.github.io/scalafmt/#IntelliJ
