### ISSUE TITLE
Different behavior when formatting files through command line and Intellij

### ISSUE THREAD

**Issue by elsap** [olafurpg/scalafmt#365]
Our team runs `sbt scalafmt` to format files and `sbt scalafmtTest` before submitting every PR so all the project files are in a pattern. 

The current `.scalafmt` file contains:

```
--maxColumn 120
```

My problem is that when I run `sbt scalafmt`, all files with `@Singleton` are formatted with `@ Singleton`, and that doesn't make sense, and, of course, CircleCI tests fails, but my `sbt scalafmtTest` passes! And when I run the formatting on Intellij, the white space between `@` and `Singleton` goes away and the test on CircleCI passes but on my machine it doesn't. What could be happening?

Using:
- 0.2.8
- --style default

**Comment by olafurpg** [comment]
Could you maybe provide a minimal repo that reproduces the sbt behavior? The annotation `@Singleton` should never be formatted as `@Singleton`.

**Comment by elsap** [comment]
I created a repo and the  `@Singleton` annotations were working fine, but then I tested another case: https://github.com/elsap/scalaTest/commit/d946054e8c977cef2b6d99f3d6b1483c7904a4b1 where there is a trait and after I set a class with the `@Singleton` annotation. As you can see in this commit, I run `sbt scalafmt` and there is a space there.

**Comment by olafurpg** [comment]
I am unable to reproduce the issue, I forked the repo and ran sbt scalafmt and the space was removed: https://github.com/olafurpg/scalaTest/commit/5106ca732de4ff73ad99db278dd59474e087c3e2 Am I missing something? Make sure you always `clean` before `scalafmt`.

**Comment by elsap** [comment]
I am the only one on my team that uses Windows and that only happens to me. You don't use Windows, right?

**Comment by olafurpg** [comment]
I'm using OSX. I struggle to see how the output on Windows can be different
than on OSX, however. Did you run clean before scalafmt?

**Comment by elsap** [comment]
Yes, I did. We've been struggling with this issue for a while now. Just now I ran `sbt clean` and `sbt scalafmt` after and my files were not formatted back (without the extra space) like yours.

**Comment by olafurpg** [comment]
Does the file format at all? If there's an exception then scalafmt leaves
the file unformatted.

**Comment by elsap** [comment]
Here is what I did:

![image](https://cloud.githubusercontent.com/assets/5271523/17229015/0cf2f9a6-54ec-11e6-8a1c-1c5f056e8008.png)

**Comment by olafurpg** [comment]
If you insert 3 spaces before Singleton, does scalafmt keep all spaces?

**Comment by elsap** [comment]
For my test app, I tried inserting 3 spaces and it formatted correctly and it didn't insert the space again. (which is very confusing) But the application I work with is really big.

**Comment by mmatloka** [comment]
> I am the only one on my team that uses Windows and that only happens to me. You don't use Windows, right?

I have seen exactly the same behaviour under Windows. Additionally files reformatted via SBT have lines endings changed from `CRLF` to `LF`. There are more differences between fromatting via sbt and intelij - generally regarding indents in many places :)

**Comment by olafurpg** [comment]
> There are more differences between fromatting via sbt and intelij - generally regarding indents in many places :)

Could you show some diffs? I struggle to understand why scalafmt would produce different output in intellij and sbt. Have you double-checked that they are running same version of scalafmt?

It's hard for me to fix this issue without anything to reproduce.

**Comment by mmatloka** [comment]
@olafurpg I've done a small debugging. It seems that the problem is related to `\r` handling. scalafmt assumes that the only newline seperator is `\n`. The raw `"\n"` occurs a lot of times in the code + I am not sure what work would have to be done to allow interpreting 2 characters instead of one as newline + tree from scala meta parser includes `\r` in tokens. I've done small experiment: https://github.com/mmatloka/scalafmt/commit/adb0335173b2046d1e38de5158a3bd00bfe277ea. This change makes some tests work + solves the `@Singleton` issue. I am not sure why it influences the annotation, I know only that without that workaround the singleton token ends with `\r`.
I am also not sure why formatting from intelij works differently. Maybe intelij does some magic with line endings?

**Comment by mmatloka** [comment]
Some other example:
`org.scalafmt.CommentTest` `javadoc docstrings are correct`
![image](https://cloud.githubusercontent.com/assets/82916/18066785/2afed0f2-6e3a-11e6-82d2-14a161e4e923.png)

**Comment by mmatloka** [comment]
And one more:
```
    val original = """@ Singleton
                     |object a {
                     |/**
                     |   * Y is cool
                     |   */
                     |val y = 2
                     |}
      """.stripMargin
    val expected = """@Singleton
                     |object a {
                     |
                     |  /**
                     |   * Y is cool
                     |   */
                     |  val y = 2
                     |}
      """.stripMargin
    val obtained = Scalafmt.format(original, javadocStyle).get
    assertNoDiff(obtained, expected)
```
![image](https://cloud.githubusercontent.com/assets/82916/18066888/9cfea966-6e3a-11e6-808c-17d6dde1d92d.png)

**Comment by olafurpg** [comment]
Aaaah, that makes a lot of sense. Scalafmt does change its behavior depending on the existence of \n, and I wouldn't be surprised if IntelliJ handles that somehow for you. Great catch @mmatloka.

Now, maybe a dumb question (I've never used Windows), but doesn't \n work on Windows just like it does on unix OSs? If so, would it be OK if scalafmt replaces all \r\n with \n and leave it that way?

**Comment by mmatloka** [comment]
Well it depends. And actually there is no universal answer :) Majority of software can read and write both \r\n and \n. Intelij allows to switch line endings (right bottom LF/CLRF).  However e.g. when using git,  there is a [setting](https://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf) allowing to checkout as \r\n and commit as \n. If scalafmt replaces all \r\n with \n, then each git checkout can make some mess (\r\n <-> \n changes appear in diffs). So acutally the solution is rather to checkout as \n and commit as \n (no changes in scalafmt needed). On the other hand https://github.com/mmatloka/scalafmt/commit/adb0335173b2046d1e38de5158a3bd00bfe277ea would work for checkout as \r\n , commit as \n, but `isWindows` method would cause a mess for people checkouting as \n and commiting as \n (because System.lineSeparator() still would be \r\n) :) Maybe the most universal way would be to check if `\r` occurs in formatted code, and if yes decide its windows, remove \r before formatting and re-add after?

**Comment by olafurpg** [comment]
Thanks for the explanation!

> Maybe the most universal way would be to check if \r occurs in formatted code, and if yes decide its windows, remove \r before formatting and re-add after?

That seems like a reasonable approach. That way, users decide whether they want \r\n or \n. Would you be interested in taking a swing at this @mmatloka?

**Comment by mmatloka** [comment]
Sure, however, I hear some little silent voice saying that making it in `Scalafmt.format` will work in practice, but still whole scalafmt build will fail on Windows with /r/n...

**Comment by olafurpg** [comment]
@elsap Could you confirm that 0.4.1 fixes this issue? @mmatloka contributed a `lineEndings` setting (with default value `unix`) that should solve this problem.

**Comment by olafurpg** [comment]
I believe @mmatloka fixed this issue. Please reopen if you still experience this problem.
