### ISSUE TITLE
Keep the breaking in new lines

### ISSUE THREAD

**Issue by joan38** [olafurpg/scalafmt#366]
Hi,

Original:
```scala
execute(request)
     .map(success => Xor.Right(success))
     .recover { case failure: Throwable => Xor.Left(failure) }
```

Scalafmt:
```scala
execute(request).map(success => Xor.Right(success)).recover { case failure: Throwable => Xor.Left(failure)
```

I would like Scalafmt to keep the breaking in new lines.

Using:
* 0.2.10
* --maxColumn 120

Thanks!

**Comment by olafurpg** [comment]
I have also experienced that scalafmt forces a select chain on a single line when I would like it to be multiline. It would be possible to skip the single line layout if there is a newline before the first select, which is `.map(...)` in this case. Scalafmt already does similar things for bodies of defs.

**Comment by olafurpg** [comment]
I think this can be fixed here: https://github.com/olafurpg/scalafmt/blob/master/core/src/main/scala/org/scalafmt/internal/Router.scala#L828

It should be something like `Split(NoSplit, 0, ignoreIf = newlines > 0)`. However, I would like to keep the default behavior the way it is, so you need to guard against some setting like  `style.keepSelectChainLineBreaks`. The setting doesn't exist yet so that needs to be added to ScalafmtStyle and Cli.

**Comment by melrief** [comment]
Pushed a [PR that solves this](https://github.com/olafurpg/scalafmt/pull/440).

**Comment by olafurpg** [comment]
Closed in #440

**Comment by joan38** [comment]
I don't quiet understand how to use this.
I can't see `keepSelectChainLineBreaks` anywhere in the doc or in the codebase.

**Comment by olafurpg** [comment]
@joan38 https://github.com/olafurpg/scalafmt/pull/440#issuecomment-249995059

**Comment by olafurpg** [comment]
There's a section in the changelog describing more about the flag

**Comment by joan38** [comment]
Thanks @olafurpg for the hint!
