### ISSUE TITLE
Regression in formatting Akka routes in 0.2.11

### ISSUE THREAD

**Issue by anna-zzz** [olafurpg/scalafmt#367]
0.2.10:
```scala
object TestRoutes {
  def routes = {
    pathPrefix("foo") {
      ???
    } ~
    pathPrefix("bar") {
      ???
    }
  }
}
```

0.2.11:
```scala
object TestRoutes {
  def routes = {
    pathPrefix("foo") {
      ???
    } ~
      pathPrefix("bar") {
        ???
      }
  }
}
```

I think that 0.2.10 formatting is the right one.

```
$ cat .scalafmt
--style defaultWithAlign
--maxColumn 100
--spaceAfterTripleEquals true
--rewriteTokens =>;⇒,<-;←,->;→
```

**Comment by olafurpg** [comment]
I see. I personally prefer the 0.2.11 output since it makes it clearer if you're missing a tilde. I guess for the next release we can allow users to specify a regexp for which infix operators should have indent, to accommodate all future needs. We then provide two defaults which mimic the 0.2.10 and 0.2.10 behaviors. Until then, you can stick on 0.2.10 :)

**Comment by olafurpg** [comment]
To enable the pre-2.11 indentation behaviour set `--indentOperators false`. This option still adds 2 space indentation for operators that match `^.*=$`, for example `+=`. If you need more customizations you can provide a regex for which operators add indentation (include filter) and which don't (exclude filter), similarly to include/exclude filters in sbt.

I should probably add clearer code examples in the docs. The docstring for scalafmtstyle is not really helpful I think.
