### ISSUE TITLE
Target directories included after 0.3.1

### ISSUE THREAD

**Issue by Checkroth** [olafurpg/scalafmt#417]
**Version**: 0.3.1
**Integration**: sbt
**Configuration**: 
```
--style defaultWithAlign
--maxColumn 80
--binPackImportSelectors true
```

With the latest update that targets higher level directories in order to include our .sbt files, scalafmt has been including compiled / generated code in formatting and formatting tests.

Our project has a directory tree that looks like:
```
├── build.sbt
├── hoge-idl
│   ├── project
│   ├── src
│   │   ├── main
│   │   │   ├── java
│   │   │   ├── resources
│   │   │   ├── scala
│   │   └── test
│   │       ├── java
│   │       ├── resources
│   │       └── scala
│   └── target
│   │   │       └── gen.thrift
│   │   └── test
│   │       ├── java
│   │       ├── resources
│   │       └── scala
│   └── target
│       ├── classes
│       │   └── gen.thrift
│       ├── resolution-cache
```

And now scalafmt  is including the target direcetory.
This causes a few problems:

- scalafmt spits out an insane amount of warnings
- scalafmt and scalafmtTest take a _very_ long time to run (20min+)
- scalafmtTest fails due to misformatted generated sources (things we don't care about formatting anyway)

Example warning:
```
[warn] Scalafmt210.scala:44      Failed to format file smoke-tests/target/scala-2.11/src_managed/main/idl/Result.scala. Cause: Search state exploded around line 64.
```

Example error:
```
[error] (project/compile:scalafmtTest) org.scalafmt.sbt.HasScalaFmt$MisformattedFile: smoke-tests/target/scala-2.11/src_managed/main/idl/Result.scala is mis-formatted.
```

**Comment by olafurpg** [comment]
Does `excludeFilter in hasScalafmt := "target*"` fix the issue?

**Comment by Checkroth** [comment]
Yes, this fixes the issue. 

It works as a temporary solution but will exclude any file that starts with "target", which isn't a problem for my project, but should be considered if anybody else applies this setting.

**Comment by olafurpg** [comment]
> should be considered if anybody else applies this setting

Correct.

I've tried with no luck to find an sbt setting to get the build definition files. I'm sure the fix is minimal, all that's needed is to replace `baseDirectory` with a more accurate setting key here: https://github.com/olafurpg/scalafmt/blob/3fab42a73449ef15153117abd9eeebd743af3049/scalafmtSbt/src/main/scala/org/scalafmt/sbt/ScalaFmtPlugin.scala#L113-L114

It's possible to test the plugin with `sbt publishLocal scripted`, see example here: https://github.com/olafurpg/scalafmt/commit/2bae4d82a4502f6714286a2ad4ff55151f763f90

I'm rather busy these days so I can't tell when I'll have time to look at this. I'm happy to help anyone who wants to take a swing at it.
