### ISSUE TITLE
feature request: remove unneeded `{ }`

### ISSUE THREAD

**Issue by johnynek** [olafurpg/scalafmt#432]
I'd love to see code like:

```scala
def foo: Int = {
  List(1, 2, 3).sum
}
```
be rewritten into
```scala
def foo: Int = List(1, 2, 3).sum
```

So, I want an option to only keep `= { }` if they are required (not a single expression).

**Comment by olafurpg** [comment]
I agree that this would be a nice feature to have. However, IMO, it belongs best in a separate tool that rewrites code as a pre-processing step before formatting. I need more time to think if we want to run those rewrites as part of scalafmt. The only benefit to that approach is that we could leverage the existing scalafmt integrations (sbt, intellij,...).

Ideally, it should be a lot easier to publish plugins that rewrite code and then compose a custom pipeline of rewrites that you want to run as part of your workflow/CI.

Incidentally, I'm working now on [scalafix](https://github.com/scalacenter/scalafix) which might be able to accommodate something like that in the future. The top priority for scalafix is Dotty, however.

**Comment by olafurpg** [comment]
What do you think about limiting this feature to methods that are implemented in a single line?

For example:

```scala
// Rewrite
def foo: Int = {
  List(1, 2, 3).sum
}
// Leave alone
def foo: Int = {
  List(1, 2, 3).map { x =>
    x + 1
  }.sum
}
```

**Comment by olafurpg** [comment]
Also, what do you think about limiting this rewrite to methods that explicitly provide a non-Unit return types. For example:


```scala
// Leave alone
def foo = {
  List(1, 2, 3).sum
}
// Leave alone
def foo: Unit = {
  println(List(1, 2, 3).sum)
}
```

**Comment by johnynek** [comment]
I personally would like to enable it regardless of number of lines or Unit
return, but some might want a more restrictive setting. Can we not do both?

Personally I find it a good encouragement to write smaller methods that can
expressed in a single expression.

**Comment by olafurpg** [comment]
We can make it configurable. Then I would like to fix #316 first.

**Comment by olafurpg** [comment]
Small update.

I tried shocon and I think it worked pretty great to start with. However, I quickly got into trouble when I wanted to read arrays of objects into my own case classes. I really don't like working with java.util.* and by the end I had implemented a mini-library for quite a bit of functionality that's already baked into circe.

I continued my work with circe-yaml and I think eventually I will go with this approach. @djspiewak I addressed some of your comments, see [here](https://github.com/olafurpg/scalafmt/blob/313999c182561acf2df7b1f55447d62d5d1504aa/cli/src/test/scala/org/scalafmt/cli/YamlSpec.scala#L44-L54). I think [configurable snake case mapping](https://meta.plasm.us/posts/2016/01/14/configuring-generic-derivation/) is on the roadmap for circe, I couldn't find any references to it on the master branch.

I am currently blocked by https://github.com/travisbrown/circe/issues/374 . My experience is that users enter typos all the time and I think scalafmt should fail on an invalid configuration file instead of silently falling back to the default settings.

**Comment by olafurpg** [comment]
Whoops, that was supposed to go into 316.

**Comment by olafurpg** [comment]
I ended up calling this rule `RedundantBraces`. It supports these settings: 
https://github.com/olafurpg/scalafmt/blob/master/core/src/main/scala/org/scalafmt/config/RedundantBracesSettings.scala

Once I release v0.4 (hopefully today, if unstable wifi allows!), I'll add instructions in the docs on how to enable/configure this new feature.

I'm optimistic that we can add other useful syntactic rewrite rules in future releases. All the infrastructure is ready now so contributing new rules should be quite straightforward.

**Comment by olafurpg** [comment]
I benchmarked the result and there seems to be a ~30% penalty for running all rewrites

```
    Formatting all of Scala.js (100k LOC):

      default  23.311 ±(99.9%) 13.058 s/op [Average]
      rewrite  29.653 ±(99.9%) 109.585 s/op [Average]
```

I suspect the performance issue has mostly to do my naive implementation of [Patch](https://github.com/olafurpg/scalafmt/blob/master/core/src/main/scala/org/scalafmt/rewrite/Patch.scala#L16-L37). We can improve this for future releases.
