### ISSUE TITLE
Feature request: keep all import selectors on single line

### ISSUE THREAD

**Issue by GMadorell** [olafurpg/scalafmt#457]
**Version**: 0.3.1
**Integration**: command line
**Configuration**: 

```
--style defaultWithAlign
--maxColumn 120
--binPackImportSelectors false
```

``` scala
package com.test.scalafmttest

import com.test.longname.longnamegain.longername.{SomeClassWhichHasAVeeeeeeeeeryLongName, LoremIpsumDolorSitAmetConsecteturAdisciping}

class ScalaFmtTest extends App {

}
```

Scalafmt:

``` scala
package com.test.scalafmttest

import com.test.longname.longnamegain.longername.{
  SomeClassWhichHasAVeeeeeeeeeryLongName,
  LoremIpsumDolorSitAmetConsecteturAdisciping
}

class ScalaFmtTest extends App {}
```

I would like the input to look like this:

``` scala
package com.test.scalafmttest

import com.test.longname.longnamegain.longername.{SomeClassWhichHasAVeeeeeeeeeryLongName, LoremIpsumDolorSitAmetConsecteturAdisciping}

class ScalaFmtTest extends App {}
```

Basically, I wanted to keep imports always on the same line, but I couldn't manage to achieve it.

**Comment by olafurpg** [comment]
There's currently no flag to get the import selectors on a single line (like scalafmt did pre-0.3). Bin packing is working as intended since the long lines are wrapped around maxColumn.

We could add a separate flag to keep the old behavior. Here's the commit that replaced the old behavior: https://github.com/olafurpg/scalafmt/commit/5a40e1451f95a63d1021389788145bbff5b14956

I think something like

```
--keepImportSelectorsOnSingleLine <bool>
```

might be enough. Still, that conflicts with --binpackimportselectors so what we might prefer is to add a `importSelectors: ImportSelectors` field to scalafmtstyle where InportSelectors is an ADT with possible values binPack, noBinPack, singleLine.

**Comment by GMadorell** [comment]
Yeah, having the three options would probably work best. How shall the argument be passed via command line, then?

**Comment by olafurpg** [comment]
For now we can do something similar to LineEndings which was added in #445. ScalafmtStyle will be reorganized soon with #453 .
