### ISSUE TITLE
Scalajs react element attributes

### ISSUE THREAD

**Issue by TimothyKlim** [olafurpg/scalafmt#458]
**Version**: 0.3.1
**Integration**: sbt
**Configuration**: `--style defaultWithAlign --maxColumn 100 --scalaDocs --continuationIndentCallSite 2`

``` scala
<.div(^.`class` := "col-xs-6",
  "text")
```

Scalafmt (**Failed to format file xxx. Cause: Search state exploded around line 1.**):

``` scala
<.div(^.`class` := "col-xs-6",
  "text")
```

I would like the input to look like this:

``` scala
<.div(^.`class` := "col-xs-6", "text")
```

Looks like `^.`class`` cause this error.

**Comment by olafurpg** [comment]
Hmm, the search state does not explode on that single line. Could you give a larger example to reproduce the bug?

Regardless, I am not surprised by the error since every one of the `<.` and `^.` opens a new search branch that causes the search space to explode sooner than on regular code.

I think there should never be a line break before a dot when the left-hand side is a symbolic operator. If you're interested in taking a swing at it, this would be an easy fix by adding a guard like `!isSymbolic(left.syntax)` here: https://github.com/olafurpg/scalafmt/blob/44116ae6f348543226d8df756258fffa53a41f9c/core/src/main/scala/org/scalafmt/internal/Router.scala#L806

Documentation on how to run the tests is here: https://github.com/olafurpg/scalafmt/blob/master/readme.md#hacking-on-scalafmt

**Comment by olafurpg** [comment]
#622 fixes all the scalajs-react dsl-related "search state exploded" errors I could find in the scalajs-react repo. It still explodes on [these lines](https://github.com/japgolly/scalajs-react/blob/fc4f1903df0e5a555827bc735a82b9f22e667492/extra/src/main/scala/japgolly/scalajs/react/extra/Reusability.scala#L286-L287) but that will have to wait for another day.

Please give v0.5 a try once it's out and let me know if it improves things for you.
