### ISSUE TITLE
scalafmt will not reformat tests by default

### ISSUE THREAD

**Issue by joan38** [olafurpg/scalafmt#518]
`sbt scalafmt` will not reformat tests by default.
We need to do `sbt test:scalafmt` (or `test:scalafmtTest`).
Is that intentional?

**Comment by joan38** [comment]
@olafurpg Do you know if this is intentional? If not can I investigate and make a PR if I find a solution?
My team got confused about why `sbt scalafmt` doesn't reformat the whole code.

**Comment by olafurpg** [comment]
This is not intentional. I don't recall this being reported before. I've honestly given up on using SBT setting keys to figure out which files to format. The current plugin seems to have a never ending long tail of issues in this space.

Feel free to investigate, the best place to start is to find a minimal repro and put it into the scripted directory. However, FYI, 0.5 will probably move to a new system that uses VCS like git to figure out which files to format. Include/exclude filters will be defined in .scalafmt.conf.

**Comment by olafurpg** [comment]
Here's how we use scalafmt in scalameta/paradise: https://github.com/scalameta/paradise/blob/master/.drone.yml#L7

No sbt plugin.

**Comment by sjrd** [comment]
The sbt plugin source code makes it pretty obvious that it *wants* to format Compile sources only under `compile:scalafmt` (aliases by sbt as `scalafmt`) and Test sources only under `test:scalafmt`. From the way it was written, I honestly thought it *was* the intended behavior, since it was so perfectly well written (the Right sbt way) to perform it that way.

If the intended behavior is to format code in all configurations, then pretty much all of `configScalafmtSettings` should be moved to `noConfigScalafmtSettings`, except the `(sourceDirectories in hasScalafmt)` setting. And in addition, add in `noConfigScalafmtSettings` the following:
```scala
(sourceDirectories in hasScalafmt) := {
  (sourceDirectories in (Compile, hasScalafmt)).value ++
  (sourceDirectories in (Test, hasScalafmt)).value
}
```

**Comment by olafurpg** [comment]
The new sbt plugin uses the CLI, which includes test sources by default.
