### ISSUE TITLE
IntelliJ plugin error messages don't appear anymore

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/scalafmt#561]
**Version**: 0.4.8
**Integration**: IntelliJ plugin

For example, if .scalafmt.conf has a typo, the plugin doesn't show emit a message with the error anymore. Can you reproduce @joan38 ?

**Comment by olafurpg** [comment]
Silly me, the error message appears in tiny font in the bottom bar:

![screen shot 2016-10-27 at 10 20 24](https://cloud.githubusercontent.com/assets/1408093/19759849/0fc6fc4c-9c2f-11e6-9750-866856405e82.png)

I'm not sure this notification system is an improvement. The previous system was way more prominent in the UI. Was there a specific reason to upgrade @joan38 ?

**Comment by olafurpg** [comment]
Alternatively, is there a way to configure the new system to be more visible in the UI? I miss the red/green/yellow info boxes 😞

**Comment by joan38** [comment]
To me this is a improvement because it uses the notification system of Idea where you get messages like that by default:
<img width="242" alt="screen shot 2016-10-27 at 09 24 16" src="https://cloud.githubusercontent.com/assets/1200478/19759995/50cd11f2-9c27-11e6-8800-ed76dc0f65e9.png">

Then you have the history in your `Event Log`:
![screen shot 2016-10-27 at 09 26 00](https://cloud.githubusercontent.com/assets/1200478/19760008/66e229e6-9c27-11e6-83f2-0865409423f1.png)

You can also set how you want to see those notifications, None, Sticky ballon or Ballon, Log them or not, Read aloud:
![screen shot 2016-10-27 at 09 26 26](https://cloud.githubusercontent.com/assets/1200478/19760027/8256a44a-9c27-11e6-9f12-f1dd81570792.png)

You must probably have wrong settings in the last screenshot.
Let me know.

**Comment by olafurpg** [comment]
As long as I get the balloons I'm happy with this new system 😄  I fixed a tiny bug where all balloons were of type information, which made it hard to distinguish errors from success messages.

We might also want to document that you need to enable balloons to for the plugin. Is there any way to enable balloons by default?

**Comment by joan38** [comment]
For me the default was "Balloon" (that disappear avec some seconds).
Perfect for the fix!

**Comment by joan38** [comment]
I just tried on the computer of a workmate who just installed it now and it's a ballon too

**Comment by olafurpg** [comment]
That's great to hear. Thanks for the quick help. I'm using 2016.3 EAP and balloons were disabled for my for some reason. I added a comment in the documentation on how to enable balloons, just in case.

**Comment by olafurpg** [comment]
That's great to hear. Thanks for the quick help. I'm using the 2016.3 EAP
and balloons were disabled for my for some reason. I added a comment in the
documentation on how to enable balloons, just in case.
