### ISSUE TITLE
State Exploded when many members

### ISSUE THREAD

**Issue by peter-empen** [olafurpg/scalafmt#582]
Hi, I get 'State exploded' for the following source:

**Version**: 0.4.9
**Integration**: intellij
**Configuration**:
style = defaultWithAlign
danglingParentheses = true
maxColumn = 120
align.openParenCallSite = true
binPack.callSite = true
binPack.defnSite = true
binPack.parentConstructors = true
binPackImportSelectors = true
indentOperator.exclude = "^(~|&&|\\|\\|)$"

```scala
  val invalidEmailValues = Set(
    "plainaddress",
    "#@%^%#$@#$@#.com",
    "@example.com",
    "Joe Smith <email@example.com>",
    "email.example.com",
    "email@example@example.com",
    ".email@example.com",
    "email.@example.com",
    "email..email@example.com",
    "あいうえお@example.com",
    "email@example.com (Joe Smith)",
    "email@example",
    "email@-example.com",
    "topLevelDomainIsAllNumeric@1234.111",
    "email@example..com",
    "65CharactersLocalPart12345678901234567890123456789012345678901234@example.com",
    "64CharactersDomainPart@123456789012345678901234567890123456789012345678901234567example.com",
    "255CharactersE-Mail@123456789012345678901234567890123456789012345678901234567890123.456789012345678901234567890123456789012345678901234567890123456.789012345678901234567890123456789012345678901234567890123456789.012345678901234567890123456789012345671.com"
  )
```

Scalafmt:
```scala
Scalafmt: Search state exploded around line x
```
To get rid of this, it suffices to remove some lines.

**Comment by olafurpg** [comment]
Yes, this is a shame. It's fixable but requires a change to the best-first search, which I avoid whenever I can. I opened #140 for this exact issue with config-style lists, since it's possible to clear the search queue on between each argument.

Your example does not trigger the error for me but any big enough argument list will typically do.

I can't promise when I'll get around to fix this. Your options for now are documented here: https://olafurpg.github.io/scalafmt/#Deeplynestedcode

**Comment by peter-empen** [comment]
thanks a lot for your timely feedback.

**Comment by olafurpg** [comment]
@peter-empen #621 fixes a large number of "search state exploded cases. Once v0.5 is out, please give it a try and see if it helps.
