### ISSUE TITLE
IntelliJ plugin doesn't appear to honor excludeFilters

### ISSUE THREAD

**Issue by sirthias** [olafurpg/scalafmt#699]
This template is a guideline, not a strict requirement.
- **Version**: 0.5.4
- **Integration**: IntelliJ
- **Configuration**:
```
project.includeFilters = [
  "core/.*\\.scala"
]
project.excludeFilters = [
  "core/src/test/scala/org/scalacheck/.*"
]
```

When "Format on Save" is enabled and the current file is saved it is reformatted regardless of whether its file name is matched by an excludeFilter or not.

**Comment by olafurpg** [comment]
Thank you for reporting! This is a bug and I suspect it should be fairly easy to fix.

If anyone wants to take a stab at it, the instructions to build the intellij plugin are here https://github.com/olafurpg/scalafmt/tree/master/intellij and the place where "format on save" takes place is here https://github.com/olafurpg/scalafmt/blob/master/intellij/src/main/scala/org/scalafmt/intellij/OnFileSaveComponent.scala#L21

The configuration can be obtained here https://github.com/olafurpg/scalafmt/blob/master/intellij/src/main/scala/org/scalafmt/intellij/IdeaUtils.scala#L44

There are no tests for the intellij plugin, since the fixture to run intellij is quite heavy.

**Comment by olafurpg** [comment]
cc/ @joan38

**Comment by olafurpg** [comment]
And btw, with a ScalafmtConfig, you can call `project.matcher.matches` to test if a file patch should be formatted or not, see https://github.com/olafurpg/scalafmt/blob/master/core/src/main/scala/org/scalafmt/config/ProjectFiles.scala#L13

**Comment by joan38** [comment]
Ah yeah I never thought about this case. That should be fairly easy to fix indeed.
I don't have time to focus on this currently but I can provide some guidance if anyone wants to do it.

**Comment by olafurpg** [comment]
"Format on save" in IntelliJ should now respect the exclude filters in .scalafmt.conf. Thank you for reporting @sirthias !

**Comment by sirthias** [comment]
Awesome! Thank you, @olafurpg!
